import os
import asyncio
import logging
from typing import Dict, Any, Optional
import sqlite3

from mcp_server.config.settings import get_settings

logger = logging.getLogger(__name__)


class LLMProviderFactory:
    """Configures LLM clients based on configuration and MCP client context."""

    @staticmethod
    def get_provider(client_name: Optional[str] = None) -> Dict[str, Any]:
        """Determine the optimal summarization model."""
        settings = get_settings()
        profiles = settings.get_semantic_profiles_config()

        # Look for summarization config in the default profile, or fallback to an empty dict
        default_profile_id = settings.get_semantic_default_profile()
        default_profile = profiles.get(default_profile_id, {})
        summary_cfg = default_profile.get("summarization", {})

        if summary_cfg.get("model_name") and summary_cfg.get("provider"):
            return summary_cfg

        # Fallback based on client
        if client_name == "claude-code" or client_name == "claude-desktop":
            return {
                "provider": "anthropic",
                "model_name": "claude-3-5-haiku-latest",
                "base_url": None,
                "api_key_env": "ANTHROPIC_API_KEY",
                "prompt_template": "Describe this code chunk's inputs, outputs, and purpose in 2 concise sentences. Do not output code.",
            }
        elif client_name in ["cursor", "windsurf"]:
            return {
                "provider": "openai",
                "model_name": "o3-mini",
                "base_url": None,
                "api_key_env": "OPENAI_API_KEY",
                "prompt_template": "Describe this code chunk's inputs, outputs, and purpose in 2 concise sentences. Do not output code.",
            }
        else:
            return {
                "provider": "openai_compatible",
                "model_name": "qwen2.5-coder:7b",
                "base_url": "http://127.0.0.1:11434/v1",
                "api_key_env": None,
                "prompt_template": "Describe this code chunk's inputs, outputs, and purpose in 2 concise sentences. Do not output code.",
            }


class ChunkWriter:
    """Base interface for semantic chunk summarization."""

    def __init__(
        self, db_path: str, qdrant_client: Any, client_name: Optional[str] = None
    ):
        self.db_path = db_path
        self.qdrant_client = qdrant_client
        self.config = LLMProviderFactory.get_provider(client_name)

    async def summarize_chunk(
        self,
        chunk_hash: str,
        file_id: int,
        chunk_start: int,
        chunk_end: int,
        symbol: str,
        content: str,
    ) -> None:
        """Fetch summary from LLM and persist to SQLite and Qdrant."""
        prompt = self.config.get(
            "prompt_template",
            "Describe this code chunk's inputs, outputs, and purpose in 2 concise sentences. Do not output code.",
        )

        # Placeholder for actual LLM call. Here you would use Anthropic or OpenAI clients
        # to fetch the generated string.
        model_name = self.config.get("model_name", "unknown")
        summary_text = f"Summary of {symbol} (Lines {chunk_start}-{chunk_end}): Generated by {model_name}."

        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT is_authoritative FROM chunk_summaries WHERE chunk_hash = ?",
                (chunk_hash,),
            )
            row = cursor.fetchone()
            if row and row[0]:
                return  # Skip, authoritative summary exists

            conn.execute(
                """INSERT INTO chunk_summaries 
                   (chunk_hash, file_id, chunk_start, chunk_end, symbol, summary_text, is_authoritative, llm_model, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, 0, ?, CURRENT_TIMESTAMP)
                   ON CONFLICT(chunk_hash) DO UPDATE SET
                   summary_text=excluded.summary_text,
                   is_authoritative=excluded.is_authoritative,
                   llm_model=excluded.llm_model,
                   updated_at=CURRENT_TIMESTAMP
                """,
                (
                    chunk_hash,
                    file_id,
                    chunk_start,
                    chunk_end,
                    symbol,
                    summary_text,
                    model_name,
                ),
            )


class ComprehensiveChunkWriter(ChunkWriter):
    """Processes entire repository."""

    async def process_all(self):
        """Find all missing summaries and generate them."""
        pass


class LazyChunkWriter(ChunkWriter):
    """Processes chunks lazily on retrieval."""

    def __init__(
        self, db_path: str, qdrant_client: Any, client_name: Optional[str] = None
    ):
        super().__init__(db_path, qdrant_client, client_name)
        self.queue = asyncio.Queue()
        self._task = None

    def start(self):
        if self._task is None:
            self._task = asyncio.create_task(self._worker())

    async def _worker(self):
        while True:
            chunk = await self.queue.get()
            try:
                await self.summarize_chunk(**chunk)
            except Exception as e:
                logger.error(f"Error summarizing chunk: {e}")
            finally:
                self.queue.task_done()

    def enqueue(self, chunk_data: Dict[str, Any]):
        self.queue.put_nowait(chunk_data)
