apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-index-mcp
  labels:
    app: code-index-mcp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-index-mcp
  template:
    metadata:
      labels:
        app: code-index-mcp
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: code-index-mcp
      containers:
      - name: code-index-mcp
        image: code-index-mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: code-index-mcp-secrets
              key: database-url
        - name: VOYAGE_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: code-index-mcp-secrets
              key: voyage-ai-api-key
              optional: true
        - name: QDRANT_URL
          valueFrom:
            configMapKeyRef:
              name: code-index-mcp-config
              key: qdrant-url
              optional: true
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: code-index-mcp-config
              key: log-level
        - name: MAX_WORKERS
          valueFrom:
            configMapKeyRef:
              name: code-index-mcp-config
              key: max-workers
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: code-index-mcp-data
      - name: config
        configMap:
          name: code-index-mcp-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-index-mcp
  labels:
    app: code-index-mcp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-index-mcp-data
  labels:
    app: code-index-mcp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd