"""SEMDOGFOOD evidence contract checks."""

from __future__ import annotations

from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
EVIDENCE = REPO / "docs" / "status" / "SEMANTIC_DOGFOOD_REBUILD.md"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _normalized(path: Path) -> str:
    return " ".join(_read(path).split())


def test_semdogfood_report_exists_and_names_required_evidence_sections():
    text = _read(EVIDENCE)

    for expected in (
        "# Semantic Dogfood Rebuild",
        "Phase plan: `plans/phase-plan-v7-SEMDOCCONTRACTTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPTAIL.md`",
        "## Reset Boundary",
        "## SEMTRACEFRESHNESS Live Trace Recovery",
        "## SEMPUBLISHRACE Live Rerun Check",
        "## SEMDEVREBOUND Live Rerun Check",
        "## SEMSCRIPTREBOUND Live Rerun Check",
        "## SEMDISKIO Live Rerun Check",
        "## SEMDEVSTALE Live Rerun Check",
        "## SEMTESTSTALE Live Rerun Check",
        "## SEMSCRIPTABORT Live Rerun Check",
        "## SEMDEVRELAPSE Live Rerun Check",
        "## SEMWALKGAP Live Rerun Check",
        "## SEMQUICKCHARTS Live Rerun Check",
        "## SEMVALIDEVIDENCE Live Rerun Check",
        "## SEMBENCHDOCS Live Rerun Check",
        "## SEMARCHIVEWALKGAP Live Rerun Check",
        "## SEMDOCGOV Live Rerun Check",
        "## SEMCLAUDECMDS Live Rerun Check",
        "## SEMSCRIPTLANGS Live Rerun Check",
        "## SEMPHASEPLANS Live Rerun Check",
        "## SEMCROSSPLANS Live Rerun Check",
        "## SEMPHASETAIL Live Rerun Check",
        "## SEMLEGACYPLANS Live Rerun Check",
        "## SEMMIXEDPHASETAIL Live Rerun Check",
        "## SEMPREUPGRADETAIL Live Rerun Check",
        "## SEMVERIFYSIMTAIL Live Rerun Check",
        "## SEMEMBEDCONSOL Live Rerun Check",
        "## SEMDOCTESTTAIL Live Rerun Check",
        "## SEMMOCKPLUGIN Live Rerun Check",
        "## SEMCODEXLOOPTAIL Live Rerun Check",
        "## SEMDOCCONTRACTTAIL Live Rerun Check",
        "## Rebuild Command",
        "## Rebuild Evidence",
        "## Repository Status",
        "## Query Comparison",
        "## Dogfood Verdict",
        "## Verification",
    ):
        assert expected in text


def test_semdogfood_report_records_trace_freshness_recovery_and_roadmap_steering():
    text = _normalized(EVIDENCE)

    for expected in (
        "SEMJEDI",
        "SEMTRACEFRESHNESS",
        "SEMPUBLISHRACE",
        "SEMDEVREBOUND",
        "SEMSCRIPTREBOUND",
        "SEMDISKIO",
        "SEMDEVSTALE",
        "SEMTESTSTALE",
        "SEMSCRIPTABORT",
        "2026-04-29T08:50:29Z",
        "2026-04-29T08:50:44Z",
        "2026-04-29T08:51:28Z",
        "2026-04-29T08:52:53Z",
        "2026-04-29T08:53:23Z",
        "2026-04-29T09:28:24Z",
        "2026-04-29T09:28:50Z",
        "2026-04-29T09:29:02Z",
        "2026-04-29T09:29:17Z",
        "2026-04-29T09:29:38Z",
        "2026-04-29T09:29:40Z",
        "2026-04-29T09:30:32Z",
        "2026-04-29T09:31:19Z",
        "2026-04-29T09:50:53Z",
        "2026-04-29T09:50:55Z",
        "2026-04-29T09:52:03Z",
        "2026-04-29T10:09:17Z",
        "2026-04-29T10:12:58Z",
        "2026-04-29T10:13:00Z",
        "2026-04-29T10:13:12Z",
        "2026-04-29T10:34:59Z",
        "2026-04-29T10:35:02Z",
        "2026-04-29T10:37:14Z",
        "2026-04-29T10:55:11Z",
        "2026-04-29T10:55:12Z",
        "2026-04-29T11:13:51Z",
        "2026-04-29T11:17:34Z",
        "2026-04-29T11:17:51Z",
        "2026-04-29T11:43:04Z",
        "2026-04-29T11:43:05Z",
        "2026-04-29T11:43:19Z",
        "2026-04-29T12:19:54Z",
        "2026-04-29T12:21:08Z",
        "2026-04-29T12:51:58Z",
        "2026-04-29T12:52:00Z",
        "2026-04-29T12:53:14Z",
        "2026-04-29T12:53:24Z",
        "2026-04-29T13:16:25Z",
        "2026-04-29T13:16:35Z",
        "2026-04-29T13:34:05Z",
        "2026-04-29T13:34:20Z",
        "2026-04-29T13:51:47Z",
        "2026-04-29T13:52:50Z",
        "2026-04-29T13:53:03Z",
        "2026-04-29T14:12:49Z",
        "2026-04-29T14:13:50Z",
        "2026-04-29T14:41:18Z",
        "2026-04-29T14:41:32Z",
        "2026-04-29T15:02:46Z",
        "2026-04-29T15:03:10Z",
        "2026-04-29T15:22:41Z",
        "2026-04-29T15:22:48Z",
        "2026-04-29T15:24:06Z",
        "2026-04-29T15:51:03Z",
        "2026-04-29T15:51:12Z",
        "2026-04-29T16:07:22Z",
        "2026-04-29T16:29:03Z",
        "2026-04-29T16:29:12Z",
        "2026-04-29T16:42:11Z",
        "2026-04-29T16:42:21Z",
        "2026-04-29T16:49:38Z",
        "2026-04-29T16:49:50Z",
        "2026-04-29T17:07:44Z",
        "2026-04-29T17:07:52Z",
        "2026-04-29T17:28:28Z",
        "2026-04-29T17:28:49Z",
        "2026-04-29T17:45:44Z",
        "2026-04-29T17:45:52Z",
        "2026-04-29T18:06:31Z",
        "2026-04-29T18:06:41Z",
        "2026-04-29T18:25:58Z",
        "2026-04-29T18:26:11Z",
        "2026-04-29T18:48:10Z",
        "2026-04-29T18:48:20Z",
        "2026-04-29T18:52:49Z",
        "2026-04-29T18:52:55Z",
        "2026-04-29T19:13:08Z",
        "2026-04-29T19:13:19Z",
        "2026-04-29T15:37:54Z",
        "2026-04-29T15:37:57Z",
        "098c1ad1",
        "40968140",
        "d0b21255",
        "705a506f",
        "7282e341",
        "9138e0b0",
        "cd2c183",
        "c8b2d724",
        "a186b352",
        "1e7a2a10",
        "aec99482",
        "8870a23f",
        "7ab3e4ca",
        "468dee18",
        "c240c23e",
        "504e419a",
        "5c0102d",
        "4133bfe",
        "2167f184",
        "6a909203",
        "40968140",
        "7335cf35",
        "ec443d85",
        "26a163da",
        "scripts/check_index_schema.py",
        "scripts/rerun_failed_native_tests.py",
        "scripts/quick_mcp_vs_native_validation.py",
        "scripts/preflight_upgrade.sh",
        "scripts/test_mcp_protocol_direct.py",
        "scripts/verify_embeddings.py",
        "scripts/claude_code_behavior_simulator.py",
        "scripts/create_semantic_embeddings.py",
        "scripts/consolidate_real_performance_data.py",
        "tests/docs/test_gaclose_evidence_closeout.py",
        "tests/docs/test_p8_deployment_security.py",
        "scripts/create_multi_repo_visual_report.py",
        "scripts/run_test_batch.py",
        "scripts/validate_mcp_comprehensive.py",
        "mcp_server/plugin_system/loader.py",
        "mcp_server/plugin_system/interfaces.py",
        "mcp_server/storage/sqlite_store.py",
        "ai_docs/jedi.md",
        "ai_docs/pytest_overview.md",
        "ai_docs/fastapi_overview.md",
        "ai_docs/plantuml_reference.md",
        ".devcontainer/post_create.sh",
        ".devcontainer/devcontainer.json",
        "tests/test_security.py",
        "tests/test_bootstrap.py",
        "tests/test_deployment_runbook_shape.py",
        "tests/test_reindex_resume.py",
        "tests/test_benchmarks.py",
        "tests/test_artifact_publish_race.py",
        "tests/root_tests/test_contextual_pipeline.py",
        "tests/root_tests/test_voyage_api.py",
        "tests/root_tests/run_reranking_tests.py",
        "tests/security/fixtures/mock_plugin/plugin.py",
        "tests/security/fixtures/mock_plugin/__init__.py",
        ".codex/phase-loop/runs/20260424T180441Z-01-gagov-execute/launch.json",
        ".codex/phase-loop/runs/20260427T071807Z-02-artpub-execute/terminal-summary.json",
        ".codex/phase-loop/runs/20260427T085911Z-02-mrready-execute/launch.json",
        ".codex/phase-loop/runs/20260427T085911Z-02-mrready-execute/heartbeat.json",
        "tests/docs/test_semincr_contract.py",
        "tests/docs/test_gabase_ga_readiness_contract.py",
        "tests/docs/test_garc_rc_soak_contract.py",
        "tests/docs/test_garel_ga_release_contract.py",
        "ai_docs/qdrant.md",
        "fast_test_results/fast_report_*.md",
        "test_workspace/real_repos/search_scaling/package.json",
        "mcp_server/visualization/__init__.py",
        "mcp_server/visualization/quick_charts.py",
        "docs/validation/ga-closeout-decision.md",
        "docs/validation/mre2e-evidence.md",
        "docs/benchmarks/mcp_vs_native_benchmark_fullrepo_fireworks_qwen_voyage_local_iter5_rerun.md",
        "docs/benchmarks/production_benchmark.md",
        "tests/root_tests/test_document_plugins.py",
        "tests/root_tests/test_real_world_repos.py",
        "analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "analysis_archive/semantic_vs_sql_comparison_1750926162.json",
        "tests/docs/test_mre2e_evidence_contract.py",
        "tests/docs/test_gagov_governance_contract.py",
        ".claude/commands/execute-lane.md",
        ".claude/commands/plan-phase.md",
        "scripts/migrate_large_index_to_multi_repo.py",
        "scripts/check_index_languages.py",
        "plans/phase-plan-v7-SEMPREFLIGHT.md",
        "plans/phase-plan-v7-SEMDOCGOV.md",
        "plans/phase-plan-v5-garecut.md",
        "plans/phase-plan-v7-SEMWALKGAP.md",
        "plans/phase-plan-v7-SEMSYNCFIX.md",
        "plans/phase-plan-v7-SEMVISUALREPORT.md",
        "plans/phase-plan-v6-WATCH.md",
        "plans/phase-plan-v1-p19.md",
        "plans/phase-plan-v7-SEMPHASETAIL.md",
        "plans/phase-plan-v5-gagov.md",
        "ai_docs/*_overview.md",
        ".devcontainer/devcontainer.json",
        "stale-running snapshot",
        "force_full_exit_trace.json",
        "code `135`",
        "disk I/O error",
        "Trace stage:",
        "Trace stage family:",
        "Trace blocker source:",
        "Older downstream assumptions should be treated as stale",
        "roadmap now adds `SEMDEVSTALE` as the nearest downstream phase",
        "roadmap now adds downstream phase `SEMWALKGAP`",
        "roadmap now adds downstream phase `SEMQUICKCHARTS`",
        "roadmap now adds downstream phase `SEMVALIDEVIDENCE`",
        "roadmap now adds downstream phase `SEMBENCHDOCS`",
        "roadmap now adds downstream phase `SEMARCHIVEWALKGAP`",
        "roadmap now adds downstream phase `SEMDOCGOV`",
        "roadmap now adds downstream phase `SEMCLAUDECMDS`",
        "roadmap now adds downstream phase `SEMSCRIPTLANGS`",
        "roadmap now adds downstream phase `SEMPHASEPLANS`",
        "roadmap now adds downstream phase `SEMCROSSPLANS`",
        "roadmap now adds downstream phase `SEMPHASETAIL`",
        "roadmap now adds downstream phase `SEMLEGACYPLANS`",
        "roadmap now adds downstream phase `SEMMIXEDPHASETAIL`",
        "roadmap now adds downstream phase `SEMPREUPGRADETAIL`",
        "roadmap now adds downstream phase `SEMVERIFYSIMTAIL`",
        "roadmap now adds downstream phase `SEMEMBEDCONSOL`",
        "roadmap now adds downstream phase `SEMDOCTESTTAIL`",
        "roadmap now adds downstream phase `SEMMOCKPLUGIN`",
        "roadmap now adds downstream phase `SEMCODEXLOOPTAIL`",
        "roadmap now adds downstream phase `SEMDOCCONTRACTTAIL`",
        "roadmap now adds downstream phase `SEMGARELTAIL`",
    ):
        assert expected in text


def test_semdogfood_report_preserves_command_level_verification_and_runtime_paths():
    text = _normalized(EVIDENCE)

    for expected in (
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or garecut or SEMWALKGAP or markdown or lexical\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or garecut or SEMWALKGAP or lexical or interrupted or boundary\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov",
        "timeout 120s env OPENAI_API_KEY=dummy-local-key uv run mcp-index repository sync --force-full",
        "env OPENAI_API_KEY=dummy-local-key uv run mcp-index repository status",
        "sed -n '1,240p' .mcp-index/force_full_exit_trace.json",
        "force_full_exit_trace.json",
        "sqlite3 .mcp-index/current.db 'select count(*) from files; select count(*) from code_chunks; select count(*) from chunk_summaries; select count(*) from semantic_points;'",
        "mcp_server/dispatcher/dispatcher_enhanced.py",
        "mcp_server/cli/repository_commands.py",
        ".devcontainer/devcontainer.json",
        "tests/test_deployment_runbook_shape.py",
        "tests/test_reindex_resume.py",
        "scripts/run_test_batch.py",
        "scripts/validate_mcp_comprehensive.py",
        "scripts/migrate_large_index_to_multi_repo.py",
        "scripts/check_index_languages.py",
        "tests/root_tests/test_voyage_api.py",
        "tests/root_tests/run_reranking_tests.py",
        "scripts/quick_mcp_vs_native_validation.py",
        "tests/test_artifact_publish_race.py",
        "analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "analysis_archive/semantic_vs_sql_comparison_1750926162.json",
        "tests/docs/test_mre2e_evidence_contract.py",
        "tests/docs/test_gagov_governance_contract.py",
        "tests/docs/test_gaclose_evidence_closeout.py",
        "tests/docs/test_p8_deployment_security.py",
        "tests/security/fixtures/mock_plugin/plugin.py",
        "tests/security/fixtures/mock_plugin/__init__.py",
        ".claude/commands/execute-lane.md",
        ".claude/commands/plan-phase.md",
        "plans/phase-plan-v7-SEMPREFLIGHT.md",
        "plans/phase-plan-v7-SEMDOCGOV.md",
        "plans/phase-plan-v5-garecut.md",
        "plans/phase-plan-v7-SEMWALKGAP.md",
        "plans/phase-plan-v7-SEMSYNCFIX.md",
        "plans/phase-plan-v7-SEMVISUALREPORT.md",
        "plans/phase-plan-v6-WATCH.md",
        "plans/phase-plan-v1-p19.md",
        "plans/phase-plan-v7-SEMPHASETAIL.md",
        "plans/phase-plan-v5-gagov.md",
        "Last sync error:",
        "disk I/O error",
        "Trace status: `interrupted`",
        "Trace stage: `lexical_walking`",
        "Trace stage family: `lexical`",
        "Trace blocker source: `lexical_mutation`",
        "semantic_source: \"semantic\"",
        "semantic_collection_name: \"code_index__oss_high__v1\"",
        "local multi-repo dogfooding",
        "Lexical boundary: using exact bounded Python indexing for mcp_server/visualization/quick_charts.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_mre2e_evidence_contract.py -> tests/docs/test_gagov_governance_contract.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_gaclose_evidence_closeout.py -> tests/docs/test_p8_deployment_security.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_semincr_contract.py -> tests/docs/test_gabase_ga_readiness_contract.py",
        "Lexical boundary: using exact bounded Python indexing for tests/security/fixtures/mock_plugin/plugin.py -> tests/security/fixtures/mock_plugin/__init__.py",
        "Lexical boundary: using exact bounded Markdown indexing for .claude/commands/execute-lane.md -> .claude/commands/plan-phase.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/validation/ga-closeout-decision.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/validation/mre2e-evidence.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/benchmarks/mcp_vs_native_benchmark_fullrepo_fireworks_qwen_voyage_local_iter5_rerun.md -> docs/benchmarks/production_benchmark.md",
        "Lexical boundary: using exact bounded Markdown indexing for plans/phase-plan-v7-SEMSYNCFIX.md -> plans/phase-plan-v7-SEMVISUALREPORT.md",
        "Lexical boundary: using exact bounded Markdown indexing for plans/phase-plan-v6-WATCH.md -> plans/phase-plan-v1-p19.md",
        "Lexical boundary: using exact bounded Markdown indexing for plans/phase-plan-v7-SEMPHASETAIL.md -> plans/phase-plan-v5-gagov.md",
        "Lexical boundary: using exact bounded Python indexing for scripts/migrate_large_index_to_multi_repo.py -> scripts/check_index_languages.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/create_semantic_embeddings.py -> scripts/consolidate_real_performance_data.py",
        "Lexical boundary: using exact bounded JSON indexing for analysis_archive/semantic_vs_sql_comparison_1750926162.json after analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "fixture repositories under test_workspace/ are ignored during lexical walking",
        "SEMPHASEPLANS acceptance is satisfied for its named blocker",
        "SEMCROSSPLANS acceptance is satisfied for its named blocker",
        "SEMPHASETAIL acceptance is satisfied for its named blocker",
        "SEMLEGACYPLANS acceptance is satisfied for its named blocker",
        "SEMMIXEDPHASETAIL acceptance is satisfied for its named blocker",
        "SEMPREUPGRADETAIL acceptance is satisfied for its named blocker",
        "SEMVERIFYSIMTAIL acceptance is satisfied for its named blocker",
        "SEMEMBEDCONSOL acceptance is satisfied for its named blocker",
        "SEMDOCTESTTAIL acceptance is satisfied for its named blocker",
        "SEMMOCKPLUGIN acceptance is satisfied for its named blocker",
        "SEMDOCCONTRACTTAIL acceptance is satisfied for its named blocker",
        "Phase plan: `plans/phase-plan-v7-SEMDOCCONTRACTTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPTAIL.md`",
        "repository status` now advertises the repaired exact bounded lexical surface",
        "Lexical boundary: using exact bounded JSON/JSONL indexing for legacy .codex/phase-loop compatibility runtime artifacts while canonical .phase-loop remains authoritative",
        "Lexical boundary: using exact bounded shell/Python indexing for scripts/preflight_upgrade.sh -> scripts/test_mcp_protocol_direct.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/verify_embeddings.py -> scripts/claude_code_behavior_simulator.py",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"create_semantic_embeddings or consolidate_real_performance_data or lexical or bounded or consolidator or script\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"create_semantic_embeddings or consolidate_real_performance_data or lexical or interrupted or boundary or consolidator or script\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"gaclose_evidence_closeout or p8_deployment_security or consolidate_real_performance_data or lexical or bounded or deployment or security or docs or consolidator\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"gaclose_evidence_closeout or p8_deployment_security or consolidate_real_performance_data or lexical or interrupted or boundary or deployment or security or docs or consolidator\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or SEMSYNCFIX or SEMVISUALREPORT or markdown or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or SEMSYNCFIX or SEMVISUALREPORT or lexical or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or WATCH or p19 or markdown or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or WATCH or p19 or lexical or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or SEMPHASETAIL or gagov or markdown or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or SEMPHASETAIL or gagov or lexical or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"preflight_upgrade or test_mcp_protocol_direct or lexical or bounded or shell or script\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"preflight_upgrade or test_mcp_protocol_direct or lexical or interrupted or boundary or script\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"verify_embeddings or claude_code_behavior_simulator or lexical or bounded or simulator or script\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"verify_embeddings or claude_code_behavior_simulator or lexical or interrupted or boundary or simulator or script\"",
        "uv run pytest tests/test_dispatcher.py tests/security/test_plugin_sandbox.py -q --no-cov -k \"mock_plugin or lexical or bounded or sandbox or fixture\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"mock_plugin or lexical or interrupted or boundary or sandbox or fixture\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"semincr or gabase or docs_contract or readiness or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"semincr or gabase or docs_contract or readiness or boundary or interrupted or lexical\"",
    ):
        assert expected in text
