"""SEMDOGFOOD evidence contract checks."""

from __future__ import annotations

from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
EVIDENCE = REPO / "docs" / "status" / "SEMANTIC_DOGFOOD_REBUILD.md"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _normalized(path: Path) -> str:
    return " ".join(_read(path).split())


def test_semdogfood_phase_loop_report_exists_and_names_required_evidence_sections():
    text = _read(EVIDENCE)

    for expected in (
        "# Semantic Dogfood Rebuild",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPREBOUNDRELAPSETAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPGARECUTHEARTBEATTAIL.md`",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPGARECUTHEARTBEATTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPRELAPSEREBOUNDTAIL.md`",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPRELAPSEREBOUNDTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPHEARTBEATTAIL.md`",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPRELAPSETAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMQUERYFULLREBOUNDTAIL.md`",
        "## Reset Boundary",
        "## SEMTRACEFRESHNESS Live Trace Recovery",
        "## SEMPUBLISHRACE Live Rerun Check",
        "## SEMDEVREBOUND Live Rerun Check",
        "## SEMSCRIPTREBOUND Live Rerun Check",
        "## SEMDISKIO Live Rerun Check",
        "## SEMDEVSTALE Live Rerun Check",
        "## SEMTESTSTALE Live Rerun Check",
        "## SEMSCRIPTABORT Live Rerun Check",
        "## SEMDEVRELAPSE Live Rerun Check",
        "## SEMWALKGAP Live Rerun Check",
        "## SEMQUICKCHARTS Live Rerun Check",
        "## SEMVALIDEVIDENCE Live Rerun Check",
        "## SEMBENCHDOCS Live Rerun Check",
        "## SEMARCHIVEWALKGAP Live Rerun Check",
        "## SEMDOCGOV Live Rerun Check",
        "## SEMCLAUDECMDS Live Rerun Check",
        "## SEMSCRIPTLANGS Live Rerun Check",
        "## SEMPHASEPLANS Live Rerun Check",
        "## SEMCROSSPLANS Live Rerun Check",
        "## SEMPHASETAIL Live Rerun Check",
        "## SEMLEGACYPLANS Live Rerun Check",
        "## SEMMIXEDPHASETAIL Live Rerun Check",
        "## SEMPREUPGRADETAIL Live Rerun Check",
        "## SEMVERIFYSIMTAIL Live Rerun Check",
        "## SEMEMBEDCONSOL Live Rerun Check",
        "## SEMDOCTESTTAIL Live Rerun Check",
        "## SEMMOCKPLUGIN Live Rerun Check",
        "## SEMCODEXLOOPTAIL Live Rerun Check",
        "## SEMDOCCONTRACTTAIL Live Rerun Check",
        "## SEMGARELTAIL Live Rerun Check",
        "## SEMDOCTRUTHTAIL Live Rerun Check",
        "## SEMSUPPORTTAIL Live Rerun Check",
        "## SEMV1PLANTAIL Live Rerun Check",
        "## SEMJEDIP4TAIL Live Rerun Check",
        "## SEMCROSSDOGTAIL Live Rerun Check",
        "## SEMFIXTURETAIL Live Rerun Check",
        "## SEMAIOVERVIEWTAIL Live Rerun Check",
        "## SEMTESTREPOINDEXTAIL Live Rerun Check",
        "## SEMMISSINGREPOSEMTAIL Live Rerun Check",
        "## SEMUTILVERIFYTAIL Live Rerun Check",
        "## SEMQDRANTREPORTTAIL Live Rerun Check",
        "## SEMOPTUPLOADTAIL Live Rerun Check",
        "## SEMEDITRETRIEVALTAIL Live Rerun Check",
        "## SEMSCRIPTLANGSTAIL Live Rerun Check",
        "## SEMQUERYFULLTAIL Live Rerun Check",
        "## SEMCODEXLOOPREBOUNDTAIL Live Rerun Check",
        "## SEMINTEGRATIONTAIL Live Rerun Check",
        "## SEMCENTRALIZETAIL Live Rerun Check",
        "## SEMQUERYFULLREBOUNDTAIL Live Rerun Check",
        "## SEMCODEXLOOPRELAPSETAIL Live Rerun Check",
        "## SEMCODEXLOOPRELAPSEREBOUNDTAIL Live Rerun Check",
        "## SEMCODEXLOOPGARECUTHEARTBEATTAIL Live Rerun Check",
        "## SEMCODEXLOOPREBOUNDRELAPSETAIL Live Rerun Check",
        "## Rebuild Command",
        "## Rebuild Evidence",
        "## Repository Status",
        "## Query Comparison",
        "## Dogfood Verdict",
        "## Verification",
    ):
        assert expected in text


def test_semdogfood_phase_loop_report_records_trace_freshness_recovery_and_roadmap_steering():
    text = _normalized(EVIDENCE)

    for expected in (
        "SEMJEDI",
        "SEMTRACEFRESHNESS",
        "SEMPUBLISHRACE",
        "SEMDEVREBOUND",
        "SEMSCRIPTREBOUND",
        "SEMDISKIO",
        "SEMDEVSTALE",
        "SEMTESTSTALE",
        "SEMSCRIPTABORT",
        "2026-04-29T08:50:29Z",
        "2026-04-29T08:50:44Z",
        "2026-04-29T08:51:28Z",
        "2026-04-29T08:52:53Z",
        "2026-04-29T08:53:23Z",
        "2026-04-29T09:28:24Z",
        "2026-04-29T09:28:50Z",
        "2026-04-29T09:29:02Z",
        "2026-04-29T09:29:17Z",
        "2026-04-29T09:29:38Z",
        "2026-04-29T09:29:40Z",
        "2026-04-29T09:30:32Z",
        "2026-04-29T09:31:19Z",
        "2026-04-29T09:50:53Z",
        "2026-04-29T09:50:55Z",
        "2026-04-29T09:52:03Z",
        "2026-04-29T10:09:17Z",
        "2026-04-29T10:12:58Z",
        "2026-04-29T10:13:00Z",
        "2026-04-29T10:13:12Z",
        "2026-04-29T10:34:59Z",
        "2026-04-29T10:35:02Z",
        "2026-04-29T10:37:14Z",
        "2026-04-29T10:55:11Z",
        "2026-04-29T10:55:12Z",
        "2026-04-29T11:13:51Z",
        "2026-04-29T11:17:34Z",
        "2026-04-29T11:17:51Z",
        "2026-04-29T11:43:04Z",
        "2026-04-29T11:43:05Z",
        "2026-04-29T11:43:19Z",
        "2026-04-29T12:19:54Z",
        "2026-04-29T12:21:08Z",
        "2026-04-29T12:51:58Z",
        "2026-04-29T12:52:00Z",
        "2026-04-29T12:53:14Z",
        "2026-04-29T12:53:24Z",
        "2026-04-29T13:16:25Z",
        "2026-04-29T13:16:35Z",
        "2026-04-29T13:34:05Z",
        "2026-04-29T13:34:20Z",
        "2026-04-29T13:51:47Z",
        "2026-04-29T13:52:50Z",
        "2026-04-29T13:53:03Z",
        "2026-04-29T14:12:49Z",
        "2026-04-29T14:13:50Z",
        "2026-04-29T14:41:18Z",
        "2026-04-29T14:41:32Z",
        "2026-04-29T15:02:46Z",
        "2026-04-29T15:03:10Z",
        "2026-04-29T15:22:41Z",
        "2026-04-29T15:22:48Z",
        "2026-04-29T15:24:06Z",
        "2026-04-29T15:51:03Z",
        "2026-04-29T15:51:12Z",
        "2026-04-29T16:07:22Z",
        "2026-04-29T16:29:03Z",
        "2026-04-29T16:29:12Z",
        "2026-04-29T16:42:11Z",
        "2026-04-29T16:42:21Z",
        "2026-04-29T16:49:38Z",
        "2026-04-29T16:49:50Z",
        "2026-04-29T17:07:44Z",
        "2026-04-29T17:07:52Z",
        "2026-04-29T17:28:28Z",
        "2026-04-29T17:28:49Z",
        "2026-04-29T17:45:44Z",
        "2026-04-29T17:45:52Z",
        "2026-04-29T18:06:31Z",
        "2026-04-29T18:06:41Z",
        "2026-04-29T18:25:58Z",
        "2026-04-29T18:26:11Z",
        "2026-04-29T18:48:10Z",
        "2026-04-29T18:48:20Z",
        "2026-04-29T18:52:49Z",
        "2026-04-29T18:52:55Z",
        "2026-04-29T19:13:08Z",
        "2026-04-29T19:13:19Z",
        "2026-04-29T19:33:07Z",
        "2026-04-29T19:33:16Z",
        "2026-04-29T19:51:51Z",
        "2026-04-29T19:52:03Z",
        "2026-04-29T20:12:35Z",
        "2026-04-29T20:12:44Z",
        "2026-04-29T20:36:26Z",
        "2026-04-29T20:36:52Z",
        "2026-04-29T20:37:15Z",
        "2026-04-29T20:38:02Z",
        "2026-04-29T20:38:17Z",
        "2026-04-29T20:58:32Z",
        "2026-04-29T20:58:40Z",
        "2026-04-30T01:52:29Z",
        "2026-04-30T02:13:36Z",
        "2026-04-30T02:14:12Z",
        "2026-04-30T03:10:06Z",
        "2026-04-30T03:26:35Z",
        "2026-04-30T03:26:49Z",
        "2026-04-30T03:45:14Z",
        "2026-04-30T04:03:43Z",
        "2026-04-30T04:04:54Z",
        "2026-04-30T04:05:03Z",
        "2026-04-29T15:37:54Z",
        "2026-04-29T15:37:57Z",
        "098c1ad1",
        "40968140",
        "d0b21255",
        "705a506f",
        "7282e341",
        "9138e0b0",
        "cd2c183",
        "c8b2d724",
        "a186b352",
        "1e7a2a10",
        "aec99482",
        "8870a23f",
        "7ab3e4ca",
        "468dee18",
        "c240c23e",
        "504e419a",
        "5c0102d",
        "4133bfe",
        "2167f184",
        "a7a71f24",
        "e78c2861",
        "dab8822a",
        "404664a1",
        "6a909203",
        "40968140",
        "7335cf35",
        "ec443d85",
        "26a163da",
        "scripts/check_index_schema.py",
        "scripts/rerun_failed_native_tests.py",
        "scripts/quick_mcp_vs_native_validation.py",
        "scripts/preflight_upgrade.sh",
        "scripts/test_mcp_protocol_direct.py",
        "scripts/verify_embeddings.py",
        "scripts/claude_code_behavior_simulator.py",
        "scripts/create_semantic_embeddings.py",
        "scripts/consolidate_real_performance_data.py",
        "tests/docs/test_gaclose_evidence_closeout.py",
        "tests/docs/test_p8_deployment_security.py",
        "scripts/create_multi_repo_visual_report.py",
        "scripts/run_test_batch.py",
        "scripts/validate_mcp_comprehensive.py",
        "mcp_server/plugin_system/loader.py",
        "mcp_server/plugin_system/interfaces.py",
        "mcp_server/storage/sqlite_store.py",
        "ai_docs/jedi.md",
        "ai_docs/pytest_overview.md",
        "ai_docs/fastapi_overview.md",
        "ai_docs/plantuml_reference.md",
        ".devcontainer/post_create.sh",
        ".devcontainer/devcontainer.json",
        "tests/test_security.py",
        "tests/test_bootstrap.py",
        "tests/test_deployment_runbook_shape.py",
        "tests/test_reindex_resume.py",
        "tests/test_benchmarks.py",
        "tests/test_artifact_publish_race.py",
        "tests/root_tests/test_contextual_pipeline.py",
        "tests/root_tests/test_voyage_api.py",
        "tests/root_tests/run_reranking_tests.py",
        "tests/security/test_route_auth_coverage.py",
        "tests/security/test_p24_sandbox_degradation.py",
        "tests/security/fixtures/mock_plugin/plugin.py",
        "tests/security/fixtures/mock_plugin/__init__.py",
        ".codex/phase-loop/runs/20260424T180441Z-01-gagov-execute/launch.json",
        ".codex/phase-loop/runs/20260427T071807Z-02-artpub-execute/terminal-summary.json",
        ".codex/phase-loop/runs/20260427T085911Z-02-mrready-execute/launch.json",
        ".codex/phase-loop/runs/20260427T085911Z-02-mrready-execute/heartbeat.json",
        ".codex/phase-loop/runs/20260424T190651Z-01-garc-plan/launch.json",
        ".codex/phase-loop/runs/20260427T075236Z-05-idxsafe-repair/terminal-summary.json",
        ".codex/phase-loop/runs/20260425T051448Z-01-garecut-execute/launch.json",
        ".codex/phase-loop/runs/20260425T051448Z-01-garecut-execute/heartbeat.json",
        "tests/docs/test_semincr_contract.py",
        "tests/docs/test_gabase_ga_readiness_contract.py",
        "tests/docs/test_garc_rc_soak_contract.py",
        "tests/docs/test_garel_ga_release_contract.py",
        "tests/docs/test_p23_doc_truth.py",
        "tests/docs/test_semdogfood_evidence_contract.py",
        "docs/markdown-table-of-contents.md",
        "docs/SUPPORT_MATRIX.md",
        "plans/phase-plan-v1-p13.md",
        "plans/phase-plan-v1-p3.md",
        "plans/phase-plan-v7-SEMJEDI.md",
        "plans/phase-plan-v1-p4.md",
        "plans/phase-plan-v7-SEMCROSSPLANS.md",
        "plans/phase-plan-v7-SEMDOGFOOD.md",
        "final_optimized_report_final_report_1750958096/final_report_data.json",
        "final_optimized_report_final_report_1750958096/FINAL_OPTIMIZED_ANALYSIS_REPORT.md",
        "ai_docs/qdrant.md",
        "fast_test_results/fast_report_*.md",
        "test_workspace/real_repos/search_scaling/package.json",
        "mcp_server/visualization/__init__.py",
        "mcp_server/visualization/quick_charts.py",
        "docs/validation/ga-closeout-decision.md",
        "docs/validation/mre2e-evidence.md",
        "docs/benchmarks/mcp_vs_native_benchmark_fullrepo_fireworks_qwen_voyage_local_iter5_rerun.md",
        "docs/benchmarks/production_benchmark.md",
        "tests/root_tests/test_document_plugins.py",
        "tests/root_tests/test_real_world_repos.py",
        "analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "analysis_archive/semantic_vs_sql_comparison_1750926162.json",
        "tests/docs/test_mre2e_evidence_contract.py",
        "tests/docs/test_gagov_governance_contract.py",
        ".claude/commands/execute-lane.md",
        ".claude/commands/plan-phase.md",
        "scripts/migrate_large_index_to_multi_repo.py",
        "scripts/check_index_languages.py",
        "plans/phase-plan-v7-SEMPREFLIGHT.md",
        "plans/phase-plan-v7-SEMDOCGOV.md",
        "plans/phase-plan-v5-garecut.md",
        "plans/phase-plan-v7-SEMWALKGAP.md",
        "plans/phase-plan-v7-SEMSYNCFIX.md",
        "plans/phase-plan-v7-SEMVISUALREPORT.md",
        "plans/phase-plan-v6-WATCH.md",
        "plans/phase-plan-v1-p19.md",
        "plans/phase-plan-v7-SEMPHASETAIL.md",
        "plans/phase-plan-v5-gagov.md",
        "ai_docs/*_overview.md",
        ".devcontainer/devcontainer.json",
        "stale-running snapshot",
        "force_full_exit_trace.json",
        "code `135`",
        "disk I/O error",
        "Trace stage:",
        "Trace stage family:",
        "Trace blocker source:",
        "Older downstream assumptions should be treated as stale",
        "roadmap now adds `SEMDEVSTALE` as the nearest downstream phase",
        "roadmap now adds downstream phase `SEMWALKGAP`",
        "roadmap now adds downstream phase `SEMVALIDEVIDENCE`",
        "roadmap now adds downstream phase `SEMBENCHDOCS`",
        "roadmap now adds downstream phase `SEMARCHIVEWALKGAP`",
        "roadmap now adds downstream phase `SEMDOCGOV`",
        "roadmap now adds downstream phase `SEMCLAUDECMDS`",
        "roadmap now adds downstream phase `SEMSCRIPTLANGS`",
        "roadmap now adds downstream phase `SEMPHASEPLANS`",
        "roadmap now adds downstream phase `SEMCROSSPLANS`",
        "roadmap now adds downstream phase `SEMPHASETAIL`",
        "roadmap now adds downstream phase `SEMLEGACYPLANS`",
        "roadmap now adds downstream phase `SEMMIXEDPHASETAIL`",
        "roadmap now adds downstream phase `SEMPREUPGRADETAIL`",
        "roadmap now adds downstream phase `SEMVERIFYSIMTAIL`",
        "roadmap now adds downstream phase `SEMEMBEDCONSOL`",
        "roadmap now adds downstream phase `SEMDOCTESTTAIL`",
        "roadmap now adds downstream phase `SEMMOCKPLUGIN`",
        "roadmap now adds downstream phase `SEMCODEXLOOPTAIL`",
        "roadmap now adds downstream phase `SEMDOCCONTRACTTAIL`",
        "roadmap now adds downstream phase `SEMGARELTAIL`",
        "roadmap now adds downstream phase `SEMDOCTRUTHTAIL`",
        "roadmap now adds downstream phase `SEMSUPPORTTAIL`",
        "roadmap now adds downstream phase `SEMV1PLANTAIL`",
        "roadmap now adds downstream phase `SEMJEDIP4TAIL`",
        "roadmap now adds downstream phase `SEMCROSSDOGTAIL`",
        "roadmap now adds downstream phase `SEMOPTREPORTTAIL`",
        "roadmap now adds downstream phase `SEMFIXTURETAIL`",
        "roadmap now adds downstream phase `SEMAIOVERVIEWTAIL`",
        "roadmap now adds downstream phase `SEMTESTREPOINDEXTAIL`",
        "roadmap now adds downstream phase `SEMMISSINGREPOSEMTAIL`",
        "roadmap now adds downstream phase `SEMUTILVERIFYTAIL`",
        "roadmap now adds downstream phase `SEMQDRANTREPORTTAIL`",
        "roadmap now adds downstream phase `SEMOPTUPLOADTAIL`",
        "roadmap now adds downstream phase `SEMEDITRETRIEVALTAIL`",
        "roadmap now adds downstream phase `SEMSCRIPTLANGSTAIL`",
        "roadmap now adds downstream phase `SEMQUERYFULLTAIL`",
        "roadmap now adds downstream phase `SEMINTEGRATIONTAIL`",
        "roadmap now adds downstream phase `SEMCENTRALIZETAIL`",
        "roadmap now adds downstream phase `SEMCODEXLOOPRELAPSETAIL`",
        "2026-04-29T21:15:40Z",
        "2026-04-29T21:15:52Z",
        "2026-04-29T21:34:54Z",
        "2026-04-29T21:35:04Z",
        "2026-04-29T21:50:51Z",
        "2026-04-29T21:51:02Z",
        "2026-04-29T22:03:19Z",
        "2026-04-29T22:04:27Z",
        "2026-04-29T22:05:44Z",
        "2026-04-29T22:08:25Z",
        "2026-04-29T22:26:54Z",
        "2026-04-29T22:27:04Z",
        "2026-04-29T22:44:06Z",
        "2026-04-29T22:44:15Z",
        "2026-04-29T23:02:12Z",
        "2026-04-29T23:02:25Z",
        "2026-04-29T23:19:13Z",
        "2026-04-29T23:19:22Z",
        "2026-04-29T23:37:26Z",
        "2026-04-29T23:37:37Z",
        "2026-04-29T23:55:48Z",
        "2026-04-29T23:55:57Z",
        "2026-04-30T00:12:10Z",
        "2026-04-30T00:12:27Z",
        "2026-04-30T00:30:12Z",
        "2026-04-30T00:30:24Z",
        "2026-04-30T00:45:43Z",
        "2026-04-30T00:46:51Z",
        "2026-04-30T01:13:32Z",
        "2026-04-30T01:13:41Z",
        "2026-04-30T01:35:03Z",
        "2026-04-30T01:51:10Z",
        "2026-04-30T01:52:29Z",
        "0195d3c",
        "d0732db6",
        "490ad260833a7a12c10e8be9a1c656f789247f9c",
        "2a439a39b168cb01571e0b0872016875d198b6e2",
        "f1c6c282d79f8835dfc4183dba430049c2a707d2",
        "cd1d50f4a7f3e563922e9eb87d2b4f6d7dd621ab",
        "96bc35b08ac83baafd50192cd8a56a22d9601a0d",
        "e6584ee5",
        "f2600b65",
        "3b92a81",
        "a0811d8a",
        "fd89efece1ff8ed78635fe1af3476c7896e96c26",
        "fe5fc6f1340da6b74fc6bd0433970ad3f568ecc0",
        "250dcd0f5bda80db857ee8f33159b323b7872faf",
        "5117d854f9272dd6c15cf071ba81d493da2d6315",
        "3406d1562464c017e5a42c9d0bcd405a07d84b96",
        "2366eb4bc22bad1e7aaa56ceee17ac8cd77d139b",
        "scripts/index_missing_repos_semantic.py",
        "scripts/identify_working_indexes.py",
        "scripts/utilities/prepare_index_for_upload.py",
        "scripts/utilities/verify_tool_usage.py",
        "scripts/map_repos_to_qdrant.py",
        "scripts/create_claude_code_aware_report.py",
        "scripts/execute_optimized_analysis.py",
        "scripts/index-artifact-upload-v2.py",
        "scripts/analyze_claude_code_edits.py",
        "scripts/verify_mcp_retrieval.py",
        "scripts/run_comprehensive_query_test.py",
        "scripts/index_all_repos_semantic_full.py",
        "tests/test_disk_full.py",
        "tests/test_incremental_indexer.py",
        "tests/integration/__init__.py",
        "tests/integration/obs/test_obs_smoke.py",
        "scripts/real_strategic_recommendations.py",
        "scripts/migrate_to_centralized.py",
        ".codex/phase-loop/runs/20260427T081107Z-08-ciflow-plan/terminal-summary.json",
        ".codex/phase-loop/runs/20260427T081107Z-08-ciflow-plan/launch.json",
        "tests/root_tests/test_swift_plugin.py",
        "tests/root_tests/test_mcp_database_efficiency.py",
    ):
        assert expected in text


def test_semdogfood_phase_loop_report_preserves_command_level_verification_and_runtime_paths():
    text = _normalized(EVIDENCE)

    for expected in (
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or garecut or SEMWALKGAP or markdown or lexical\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or garecut or SEMWALKGAP or lexical or interrupted or boundary\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov",
        "timeout 120s env OPENAI_API_KEY=dummy-local-key uv run mcp-index repository sync --force-full",
        "env OPENAI_API_KEY=dummy-local-key uv run mcp-index repository status",
        "sed -n '1,240p' .mcp-index/force_full_exit_trace.json",
        "force_full_exit_trace.json",
        "sqlite3 .mcp-index/current.db 'select count(*) from files; select count(*) from code_chunks; select count(*) from chunk_summaries; select count(*) from semantic_points;'",
        "mcp_server/dispatcher/dispatcher_enhanced.py",
        "mcp_server/cli/repository_commands.py",
        ".devcontainer/devcontainer.json",
        "tests/test_deployment_runbook_shape.py",
        "tests/test_reindex_resume.py",
        "scripts/run_test_batch.py",
        "scripts/validate_mcp_comprehensive.py",
        "scripts/migrate_large_index_to_multi_repo.py",
        "scripts/check_index_languages.py",
        "tests/root_tests/test_voyage_api.py",
        "tests/root_tests/run_reranking_tests.py",
        "scripts/quick_mcp_vs_native_validation.py",
        "scripts/check_test_index_schema.py",
        "scripts/ensure_test_repos_indexed.py",
        "scripts/index_missing_repos_semantic.py",
        "scripts/identify_working_indexes.py",
        "scripts/utilities/prepare_index_for_upload.py",
        "scripts/utilities/verify_tool_usage.py",
        "scripts/map_repos_to_qdrant.py",
        "scripts/create_claude_code_aware_report.py",
        "scripts/execute_optimized_analysis.py",
        "scripts/index-artifact-upload-v2.py",
        "scripts/analyze_claude_code_edits.py",
        "scripts/verify_mcp_retrieval.py",
        "scripts/migrate_large_index_to_multi_repo.py",
        "scripts/check_index_languages.py",
        "tests/test_artifact_publish_race.py",
        "analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "analysis_archive/semantic_vs_sql_comparison_1750926162.json",
        "tests/docs/test_mre2e_evidence_contract.py",
        "tests/docs/test_gagov_governance_contract.py",
        "tests/docs/test_gaclose_evidence_closeout.py",
        "tests/docs/test_p8_deployment_security.py",
        "tests/security/fixtures/mock_plugin/plugin.py",
        "tests/security/fixtures/mock_plugin/__init__.py",
        ".claude/commands/execute-lane.md",
        ".claude/commands/plan-phase.md",
        "plans/phase-plan-v7-SEMPREFLIGHT.md",
        "plans/phase-plan-v7-SEMDOCGOV.md",
        "plans/phase-plan-v5-garecut.md",
        "plans/phase-plan-v7-SEMWALKGAP.md",
        "plans/phase-plan-v7-SEMSYNCFIX.md",
        "plans/phase-plan-v7-SEMVISUALREPORT.md",
        "plans/phase-plan-v6-WATCH.md",
        "plans/phase-plan-v1-p19.md",
        "plans/phase-plan-v7-SEMPHASETAIL.md",
        "plans/phase-plan-v5-gagov.md",
        "Last sync error:",
        "disk I/O error",
        "Trace status: `interrupted`",
        "Trace stage: `lexical_walking`",
        "Trace stage family: `lexical`",
        "Trace blocker source: `lexical_mutation`",
        "semantic_source: \"semantic\"",
        "semantic_collection_name: \"code_index__oss_high__v1\"",
        "local multi-repo dogfooding",
        "Lexical boundary: using exact bounded Python indexing for mcp_server/visualization/quick_charts.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_mre2e_evidence_contract.py -> tests/docs/test_gagov_governance_contract.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_gaclose_evidence_closeout.py -> tests/docs/test_p8_deployment_security.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_semincr_contract.py -> tests/docs/test_gabase_ga_readiness_contract.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_garc_rc_soak_contract.py -> tests/docs/test_garel_ga_release_contract.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_p23_doc_truth.py -> tests/docs/test_semdogfood_evidence_contract.py",
        "Lexical boundary: using exact bounded Python indexing for tests/security/test_route_auth_coverage.py -> tests/security/test_p24_sandbox_degradation.py",
        "Lexical boundary: using exact bounded Python indexing for tests/security/fixtures/mock_plugin/plugin.py -> tests/security/fixtures/mock_plugin/__init__.py",
        "Lexical boundary: using exact bounded Markdown indexing for .claude/commands/execute-lane.md -> .claude/commands/plan-phase.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/validation/ga-closeout-decision.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/validation/mre2e-evidence.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/benchmarks/mcp_vs_native_benchmark_fullrepo_fireworks_qwen_voyage_local_iter5_rerun.md -> docs/benchmarks/production_benchmark.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/markdown-table-of-contents.md -> docs/SUPPORT_MATRIX.md",
        "Lexical boundary: using exact bounded Markdown indexing for plans/phase-plan-v7-SEMSYNCFIX.md -> plans/phase-plan-v7-SEMVISUALREPORT.md",
        "Lexical boundary: using exact bounded Markdown indexing for plans/phase-plan-v6-WATCH.md -> plans/phase-plan-v1-p19.md",
        "Lexical boundary: using exact bounded Markdown indexing for plans/phase-plan-v1-p13.md -> plans/phase-plan-v1-p3.md",
        "Lexical boundary: using exact bounded Markdown indexing for plans/phase-plan-v7-SEMPHASETAIL.md -> plans/phase-plan-v5-gagov.md",
        "Lexical boundary: using exact bounded Python indexing for scripts/migrate_large_index_to_multi_repo.py -> scripts/check_index_languages.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/create_semantic_embeddings.py -> scripts/consolidate_real_performance_data.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/check_test_index_schema.py -> scripts/ensure_test_repos_indexed.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/index_missing_repos_semantic.py -> scripts/identify_working_indexes.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/utilities/prepare_index_for_upload.py -> scripts/utilities/verify_tool_usage.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/analyze_claude_code_edits.py -> scripts/verify_mcp_retrieval.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/execute_optimized_analysis.py -> scripts/index-artifact-upload-v2.py",
        "Lexical boundary: using exact bounded JSON indexing for analysis_archive/semantic_vs_sql_comparison_1750926162.json after analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "Lexical boundary: using exact bounded JSON indexing for final_optimized_report_final_report_1750958096/final_report_data.json -> final_optimized_report_final_report_1750958096/FINAL_OPTIMIZED_ANALYSIS_REPORT.md",
        "fixture repositories under test_workspace/ are ignored during lexical walking",
        "SEMPHASEPLANS acceptance is satisfied for its named blocker",
        "SEMCROSSPLANS acceptance is satisfied for its named blocker",
        "SEMPHASETAIL acceptance is satisfied for its named blocker",
        "SEMLEGACYPLANS acceptance is satisfied for its named blocker",
        "SEMMIXEDPHASETAIL acceptance is satisfied for its named blocker",
        "SEMPREUPGRADETAIL acceptance is satisfied for its named blocker",
        "SEMVERIFYSIMTAIL acceptance is satisfied for its named blocker",
        "SEMEMBEDCONSOL acceptance is satisfied for its named blocker",
        "SEMDOCTESTTAIL acceptance is satisfied for its named blocker",
        "SEMMOCKPLUGIN acceptance is satisfied for its named blocker",
        "SEMDOCCONTRACTTAIL acceptance is satisfied for its named blocker",
        "SEMGARELTAIL acceptance is satisfied for its named blocker",
        "SEMDOCTRUTHTAIL acceptance is satisfied for its named blocker",
        "SEMSUPPORTTAIL acceptance is satisfied for its named blocker",
        "SEMV1PLANTAIL acceptance is satisfied for its named blocker",
        "SEMCROSSDOGTAIL acceptance is satisfied for its named blocker",
        "SEMOPTREPORTTAIL acceptance is satisfied for its named blocker",
        "SEMQDRANTREPORTTAIL acceptance is satisfied for its named blocker",
        "SEMOPTUPLOADTAIL acceptance is satisfied for its named blocker",
        "SEMEDITRETRIEVALTAIL acceptance is satisfied for its named blocker",
        "SEMSCRIPTLANGSTAIL acceptance is satisfied for its named blocker",
        "SEMCODEXLOOPREBOUNDTAIL acceptance is satisfied for its named blocker",
        "SEMINTEGRATIONTAIL acceptance is satisfied for its named blocker",
        "SEMCENTRALIZETAIL acceptance is satisfied for its named blocker",
        "SEMQUERYFULLREBOUNDTAIL acceptance is satisfied for its named blocker",
        "SEMCODEXLOOPRELAPSETAIL acceptance is satisfied for its named blocker",
        "SEMSECAUTHSANDBOXTAIL acceptance is satisfied for its named blocker",
        "SEMCODEXLOOPHEARTBEATTAIL acceptance is satisfied for its named blocker",
        "SEMCODEXLOOPRELAPSEREBOUNDTAIL acceptance is satisfied for its named blocker",
        "SEMCODEXLOOPREBOUNDRELAPSETAIL acceptance is satisfied for its named blocker",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPREBOUNDRELAPSETAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPGARECUTHEARTBEATTAIL.md`",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPRELAPSEREBOUNDTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPHEARTBEATTAIL.md`",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPHEARTBEATTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMSECAUTHSANDBOXTAIL.md`",
        "Phase plan: `plans/phase-plan-v7-SEMCODEXLOOPRELAPSETAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMQUERYFULLREBOUNDTAIL.md`",
        "roadmap now adds downstream phase `SEMQUERYFULLREBOUNDTAIL`",
        "roadmap now adds downstream phase `SEMCODEXLOOPRELAPSETAIL`",
        "roadmap now adds downstream phase `SEMSWIFTDBEFFTAIL`",
        "roadmap now adds downstream phase `SEMSECAUTHSANDBOXTAIL`",
        "roadmap now adds downstream phase `SEMCODEXLOOPHEARTBEATTAIL`",
        "roadmap now adds downstream phase `SEMCODEXLOOPRELAPSEREBOUNDTAIL`",
        "roadmap now adds downstream phase `SEMCODEXLOOPGARECUTHEARTBEATTAIL`",
        "roadmap now adds downstream phase `SEMCODEXLOOPREBOUNDRELAPSETAIL`",
        "roadmap now adds downstream phase `SEMCODEXLOOPCIFLOWEXECRELAPSETAIL`",
        "scripts/run_comprehensive_query_test.py",
        "scripts/index_all_repos_semantic_full.py",
        ".codex/phase-loop/runs/20260427T081107Z-08-ciflow-plan/terminal-summary.json",
        ".codex/phase-loop/runs/20260427T081107Z-08-ciflow-plan/launch.json",
        ".codex/phase-loop/runs/20260427T071207Z-01-artpub-plan/launch.json",
        ".codex/phase-loop/runs/20260427T071207Z-01-artpub-plan/heartbeat.json",
        ".codex/phase-loop/runs/20260425T051448Z-01-garecut-execute/launch.json",
        ".codex/phase-loop/runs/20260425T051448Z-01-garecut-execute/heartbeat.json",
        ".codex/phase-loop/runs/20260424T190651Z-01-garc-plan/launch.json",
        ".codex/phase-loop/runs/20260427T075236Z-05-idxsafe-repair/terminal-summary.json",
        ".codex/phase-loop/runs/20260427T081704Z-09-ciflow-execute/terminal-summary.json",
        ".codex/phase-loop/runs/20260427T081704Z-09-ciflow-execute/launch.json",
        "## SEMCODEXLOOPHEARTBEATTAIL Live Rerun Check",
        "## SEMCODEXLOOPRELAPSEREBOUNDTAIL Live Rerun Check",
        "## SEMCODEXLOOPGARECUTHEARTBEATTAIL Live Rerun Check",
        "## SEMCODEXLOOPREBOUNDRELAPSETAIL Live Rerun Check",
        "tests/root_tests/test_swift_plugin.py",
        "tests/root_tests/test_mcp_database_efficiency.py",
        "Phase plan: `plans/phase-plan-v7-SEMSWIFTDBEFFTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMCODEXLOOPRELAPSETAIL.md`",
        "Phase plan: `plans/phase-plan-v7-SEMSECAUTHSANDBOXTAIL.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMSWIFTDBEFFTAIL.md`",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"run_comprehensive_query_test or index_all_repos_semantic_full or comprehensive_query or full_semantic or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"run_comprehensive_query_test or index_all_repos_semantic_full or comprehensive_query or full_semantic or lexical or interrupted or boundary or closeout_handoff\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMCENTRALIZETAIL or SEMQUERYFULLREBOUNDTAIL or run_comprehensive_query_test or index_all_repos_semantic_full\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"swift_plugin or database_efficiency or root_test or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"swift_plugin or database_efficiency or root_test or interrupted or boundary or closeout_handoff\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMCODEXLOOPRELAPSETAIL or SEMSWIFTDBEFFTAIL or swift_plugin or database_efficiency\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"route_auth or sandbox_degradation or security or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"route_auth or sandbox_degradation or security or interrupted or boundary or closeout_handoff\"",
        "uv run pytest tests/security/test_route_auth_coverage.py tests/security/test_p24_sandbox_degradation.py -q --no-cov",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMSWIFTDBEFFTAIL or SEMSECAUTHSANDBOXTAIL or route_auth or sandbox_degradation or security\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"artpub or heartbeat or legacy_codex_phase_loop or bounded or phase_loop\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"artpub or heartbeat or legacy_codex_phase_loop or interrupted or boundary or closeout_handoff or phase_loop\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMSECAUTHSANDBOXTAIL or SEMCODEXLOOPHEARTBEATTAIL or heartbeat or phase_loop\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"ciflow or terminal_summary or launch or heartbeat or legacy_codex_phase_loop or bounded or phase_loop\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"ciflow or heartbeat or legacy_codex_phase_loop or interrupted or boundary or closeout_handoff or phase_loop\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMCODEXLOOPHEARTBEATTAIL or SEMCODEXLOOPRELAPSEREBOUNDTAIL or ciflow or phase_loop\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"ciflow or legacy_codex_phase_loop or terminal_summary or launch or bounded or phase_loop\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"ciflow or legacy_codex_phase_loop or interrupted or boundary or closeout_handoff or phase_loop\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMQUERYFULLREBOUNDTAIL or SEMCODEXLOOPRELAPSETAIL or phase_loop\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"garecut or heartbeat or legacy_codex_phase_loop or bounded or phase_loop\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"garecut or heartbeat or legacy_codex_phase_loop or interrupted or boundary or closeout_handoff or phase_loop\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMCODEXLOOPRELAPSEREBOUNDTAIL or SEMCODEXLOOPGARECUTHEARTBEATTAIL or garecut or phase_loop\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"garc or idxsafe or legacy_codex_phase_loop or terminal_summary or launch or bounded or phase_loop\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"garc or idxsafe or legacy_codex_phase_loop or interrupted or boundary or closeout_handoff or phase_loop\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMQUERYFULLTAIL or SEMCODEXLOOPREBOUNDTAIL or phase_loop or garc or idxsafe\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"garc or idxsafe or garecut or legacy_codex_phase_loop or terminal_summary or launch or bounded or phase_loop\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"garc or idxsafe or garecut or legacy_codex_phase_loop or interrupted or boundary or closeout_handoff or phase_loop\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMCODEXLOOPGARECUTHEARTBEATTAIL or SEMCODEXLOOPREBOUNDRELAPSETAIL or garc or idxsafe or phase_loop\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"integration_init or obs_smoke or integration_tail or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"integration_init or obs_smoke or integration_tail or interrupted or boundary or closeout_handoff\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMINTEGRATIONTAIL or SEMCODEXLOOPREBOUNDTAIL or obs_smoke or integration\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"real_strategic or migrate_to_centralized or centralize_tail or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"real_strategic or migrate_to_centralized or centralize_tail or interrupted or boundary or closeout_handoff\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMINTEGRATIONTAIL or SEMCENTRALIZETAIL or real_strategic or migrate_to_centralized\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"migrate_large_index_to_multi_repo or check_index_languages or script_language_audit or rebound or closeout_handoff or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"migrate_large_index_to_multi_repo or check_index_languages or script_language_audit or rebound or closeout or interrupted or boundary\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMSCRIPTLANGSTAIL or SEMEDITRETRIEVALTAIL or migrate_large_index_to_multi_repo or check_index_languages or script_language_audit\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"analyze_claude_code_edits or verify_mcp_retrieval or retrieval or transcript or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"analyze_claude_code_edits or verify_mcp_retrieval or retrieval or transcript or lexical or interrupted or boundary\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMEDITRETRIEVALTAIL or analyze_claude_code_edits or verify_mcp_retrieval or retrieval\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"execute_optimized_analysis or index_artifact_upload or upload or optimized or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"execute_optimized_analysis or index_artifact_upload or upload or optimized or lexical or interrupted or boundary\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov -k \"SEMOPTUPLOADTAIL or execute_optimized_analysis or index_artifact_upload or upload\"",
        "repository status` now advertises the repaired exact bounded lexical surface",
        "Lexical boundary: using exact bounded JSON/JSONL indexing for legacy .codex/phase-loop compatibility runtime artifacts while canonical .phase-loop remains authoritative",
        "Lexical boundary: using exact bounded shell/Python indexing for scripts/preflight_upgrade.sh -> scripts/test_mcp_protocol_direct.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/verify_embeddings.py -> scripts/claude_code_behavior_simulator.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/map_repos_to_qdrant.py -> scripts/create_claude_code_aware_report.py",
        "Lexical boundary: using exact bounded Python indexing for scripts/execute_optimized_analysis.py -> scripts/index-artifact-upload-v2.py",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"create_semantic_embeddings or consolidate_real_performance_data or lexical or bounded or consolidator or script\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"create_semantic_embeddings or consolidate_real_performance_data or lexical or interrupted or boundary or consolidator or script\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"gaclose_evidence_closeout or p8_deployment_security or consolidate_real_performance_data or lexical or bounded or deployment or security or docs or consolidator\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"gaclose_evidence_closeout or p8_deployment_security or consolidate_real_performance_data or lexical or interrupted or boundary or deployment or security or docs or consolidator\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or SEMSYNCFIX or SEMVISUALREPORT or markdown or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or SEMSYNCFIX or SEMVISUALREPORT or lexical or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or WATCH or p19 or markdown or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or WATCH or p19 or lexical or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"p13 or p3 or historical_v1_phase_plan_pair\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"p13 or p3 or historical_v1_phase_plan_pair or historical_v1_phase_plan_markdown_boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or SEMPHASETAIL or gagov or markdown or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or SEMPHASETAIL or gagov or lexical or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"preflight_upgrade or test_mcp_protocol_direct or lexical or bounded or shell or script\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"preflight_upgrade or test_mcp_protocol_direct or lexical or interrupted or boundary or script\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"verify_embeddings or claude_code_behavior_simulator or lexical or bounded or simulator or script\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"verify_embeddings or claude_code_behavior_simulator or lexical or interrupted or boundary or simulator or script\"",
        "uv run pytest tests/test_dispatcher.py tests/security/test_plugin_sandbox.py -q --no-cov -k \"mock_plugin or lexical or bounded or sandbox or fixture\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"mock_plugin or lexical or interrupted or boundary or sandbox or fixture\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"semincr or gabase or docs_contract or readiness or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"semincr or gabase or docs_contract or readiness or boundary or interrupted or lexical\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"garc or garel or ga_release or rc_soak or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"garc or garel or ga_release or rc_soak or boundary or interrupted or lexical\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"p23 or semdogfood or doc_truth or evidence_contract or lexical or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"p23 or semdogfood or doc_truth or evidence_contract or boundary or interrupted or lexical\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"support_matrix or markdown_table_of_contents or support_docs or markdown or bounded\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"support_matrix or markdown_table_of_contents or support_docs or lexical or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"optimized_final_report or final_report_data or analysis_report\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"optimized_final_report or final_report_data or analysis_report or interrupted or boundary\"",
        "uv run pytest tests/test_dispatcher.py tests/root_tests/test_markdown_production_scenarios.py -q --no-cov -k \"black_isort or sqlite_fts5 or overview or ai_docs or markdown\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"black_isort or sqlite_fts5 or overview or lexical or interrupted or boundary\"",
        "uv run pytest tests/docs/test_p23_doc_truth.py tests/docs/test_semdogfood_evidence_contract.py -q --no-cov",
        "tests/fixtures/multi_repo.py",
        "tests/fixtures/files/test_files/example.c",
        "ai_docs/black_isort_overview.md",
        "ai_docs/sqlite_fts5_overview.md",
        "SEMFIXTURETAIL acceptance is satisfied for its named blocker",
        "SEMAIOVERVIEWTAIL acceptance is satisfied for its named blocker",
        "SEMTESTREPOINDEXTAIL acceptance is satisfied for its named blocker",
        "SEMMISSINGREPOSEMTAIL acceptance is satisfied for its named blocker",
        "SEMUTILVERIFYTAIL acceptance is satisfied for its named blocker",
    ):
        assert expected in text
