"""SEMDOGFOOD evidence contract checks."""

from __future__ import annotations

from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
EVIDENCE = REPO / "docs" / "status" / "SEMANTIC_DOGFOOD_REBUILD.md"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _normalized(path: Path) -> str:
    return " ".join(_read(path).split())


def test_semdogfood_report_exists_and_names_required_evidence_sections():
    text = _read(EVIDENCE)

    for expected in (
        "# Semantic Dogfood Rebuild",
        "Phase plan: `plans/phase-plan-v7-SEMCROSSPLANS.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMPHASEPLANS.md`",
        "## Reset Boundary",
        "## SEMTRACEFRESHNESS Live Trace Recovery",
        "## SEMPUBLISHRACE Live Rerun Check",
        "## SEMDEVREBOUND Live Rerun Check",
        "## SEMSCRIPTREBOUND Live Rerun Check",
        "## SEMDISKIO Live Rerun Check",
        "## SEMDEVSTALE Live Rerun Check",
        "## SEMTESTSTALE Live Rerun Check",
        "## SEMSCRIPTABORT Live Rerun Check",
        "## SEMDEVRELAPSE Live Rerun Check",
        "## SEMWALKGAP Live Rerun Check",
        "## SEMQUICKCHARTS Live Rerun Check",
        "## SEMVALIDEVIDENCE Live Rerun Check",
        "## SEMBENCHDOCS Live Rerun Check",
        "## SEMARCHIVEWALKGAP Live Rerun Check",
        "## SEMDOCGOV Live Rerun Check",
        "## SEMCLAUDECMDS Live Rerun Check",
        "## SEMSCRIPTLANGS Live Rerun Check",
        "## SEMPHASEPLANS Live Rerun Check",
        "## SEMCROSSPLANS Live Rerun Check",
        "## Rebuild Command",
        "## Rebuild Evidence",
        "## Repository Status",
        "## Query Comparison",
        "## Dogfood Verdict",
        "## Verification",
    ):
        assert expected in text


def test_semdogfood_report_records_trace_freshness_recovery_and_roadmap_steering():
    text = _normalized(EVIDENCE)

    for expected in (
        "SEMJEDI",
        "SEMTRACEFRESHNESS",
        "SEMPUBLISHRACE",
        "SEMDEVREBOUND",
        "SEMSCRIPTREBOUND",
        "SEMDISKIO",
        "SEMDEVSTALE",
        "SEMTESTSTALE",
        "SEMSCRIPTABORT",
        "2026-04-29T08:50:29Z",
        "2026-04-29T08:50:44Z",
        "2026-04-29T08:51:28Z",
        "2026-04-29T08:52:53Z",
        "2026-04-29T08:53:23Z",
        "2026-04-29T09:28:24Z",
        "2026-04-29T09:28:50Z",
        "2026-04-29T09:29:02Z",
        "2026-04-29T09:29:17Z",
        "2026-04-29T09:29:38Z",
        "2026-04-29T09:29:40Z",
        "2026-04-29T09:30:32Z",
        "2026-04-29T09:31:19Z",
        "2026-04-29T09:50:53Z",
        "2026-04-29T09:50:55Z",
        "2026-04-29T09:52:03Z",
        "2026-04-29T10:09:17Z",
        "2026-04-29T10:12:58Z",
        "2026-04-29T10:13:00Z",
        "2026-04-29T10:13:12Z",
        "2026-04-29T10:34:59Z",
        "2026-04-29T10:35:02Z",
        "2026-04-29T10:37:14Z",
        "2026-04-29T10:55:11Z",
        "2026-04-29T10:55:12Z",
        "2026-04-29T11:13:51Z",
        "2026-04-29T11:17:34Z",
        "2026-04-29T11:17:51Z",
        "2026-04-29T11:43:04Z",
        "2026-04-29T11:43:05Z",
        "2026-04-29T11:43:19Z",
        "2026-04-29T12:19:54Z",
        "2026-04-29T12:21:08Z",
        "2026-04-29T12:51:58Z",
        "2026-04-29T12:52:00Z",
        "2026-04-29T12:53:14Z",
        "2026-04-29T12:53:24Z",
        "2026-04-29T13:16:25Z",
        "2026-04-29T13:16:35Z",
        "2026-04-29T13:34:05Z",
        "2026-04-29T13:34:20Z",
        "2026-04-29T13:51:47Z",
        "2026-04-29T13:52:50Z",
        "2026-04-29T13:53:03Z",
        "2026-04-29T14:12:49Z",
        "2026-04-29T14:13:50Z",
        "2026-04-29T14:41:18Z",
        "2026-04-29T14:41:32Z",
        "2026-04-29T15:02:46Z",
        "2026-04-29T15:03:10Z",
        "2026-04-29T15:22:41Z",
        "2026-04-29T15:22:48Z",
        "2026-04-29T15:24:06Z",
        "2026-04-29T15:51:03Z",
        "2026-04-29T15:51:12Z",
        "2026-04-29T15:37:54Z",
        "2026-04-29T15:37:57Z",
        "098c1ad1",
        "40968140",
        "d0b21255",
        "705a506f",
        "7282e341",
        "9138e0b0",
        "cd2c183",
        "c8b2d724",
        "a186b352",
        "1e7a2a10",
        "aec99482",
        "8870a23f",
        "40968140",
        "7335cf35",
        "ec443d85",
        "26a163da",
        "scripts/check_index_schema.py",
        "scripts/rerun_failed_native_tests.py",
        "scripts/quick_mcp_vs_native_validation.py",
        "scripts/create_multi_repo_visual_report.py",
        "scripts/run_test_batch.py",
        "scripts/validate_mcp_comprehensive.py",
        "mcp_server/plugin_system/loader.py",
        "mcp_server/plugin_system/interfaces.py",
        "mcp_server/storage/sqlite_store.py",
        "ai_docs/jedi.md",
        "ai_docs/pytest_overview.md",
        "ai_docs/fastapi_overview.md",
        "ai_docs/plantuml_reference.md",
        ".devcontainer/post_create.sh",
        ".devcontainer/devcontainer.json",
        "tests/test_security.py",
        "tests/test_bootstrap.py",
        "tests/test_deployment_runbook_shape.py",
        "tests/test_reindex_resume.py",
        "tests/test_benchmarks.py",
        "tests/test_artifact_publish_race.py",
        "tests/root_tests/test_contextual_pipeline.py",
        "tests/root_tests/test_voyage_api.py",
        "tests/root_tests/run_reranking_tests.py",
        "tests/security/fixtures/mock_plugin/plugin.py",
        "ai_docs/qdrant.md",
        "fast_test_results/fast_report_*.md",
        "test_workspace/real_repos/search_scaling/package.json",
        "mcp_server/visualization/__init__.py",
        "mcp_server/visualization/quick_charts.py",
        "docs/validation/ga-closeout-decision.md",
        "docs/validation/mre2e-evidence.md",
        "docs/benchmarks/mcp_vs_native_benchmark_fullrepo_fireworks_qwen_voyage_local_iter5_rerun.md",
        "docs/benchmarks/production_benchmark.md",
        "tests/root_tests/test_document_plugins.py",
        "tests/root_tests/test_real_world_repos.py",
        "analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "analysis_archive/semantic_vs_sql_comparison_1750926162.json",
        "tests/docs/test_mre2e_evidence_contract.py",
        "tests/docs/test_gagov_governance_contract.py",
        ".claude/commands/execute-lane.md",
        ".claude/commands/plan-phase.md",
        "scripts/migrate_large_index_to_multi_repo.py",
        "scripts/check_index_languages.py",
        "plans/phase-plan-v7-SEMPREFLIGHT.md",
        "plans/phase-plan-v7-SEMDOCGOV.md",
        "plans/phase-plan-v5-garecut.md",
        "plans/phase-plan-v7-SEMWALKGAP.md",
        "plans/phase-plan-v7-SEMSYNCFIX.md",
        "plans/phase-plan-v7-SEMVISUALREPORT.md",
        "ai_docs/*_overview.md",
        ".devcontainer/devcontainer.json",
        "stale-running snapshot",
        "force_full_exit_trace.json",
        "code `135`",
        "disk I/O error",
        "Trace stage:",
        "Trace stage family:",
        "Trace blocker source:",
        "Older downstream assumptions should be treated as stale",
        "roadmap now adds `SEMDEVSTALE` as the nearest downstream phase",
        "roadmap now adds downstream phase `SEMWALKGAP`",
        "roadmap now adds downstream phase `SEMQUICKCHARTS`",
        "roadmap now adds downstream phase `SEMVALIDEVIDENCE`",
        "roadmap now adds downstream phase `SEMBENCHDOCS`",
        "roadmap now adds downstream phase `SEMARCHIVEWALKGAP`",
        "roadmap now adds downstream phase `SEMDOCGOV`",
        "roadmap now adds downstream phase `SEMCLAUDECMDS`",
        "roadmap now adds downstream phase `SEMSCRIPTLANGS`",
        "roadmap now adds downstream phase `SEMPHASEPLANS`",
        "roadmap now adds downstream phase `SEMCROSSPLANS`",
        "roadmap now adds downstream phase `SEMPHASETAIL`",
    ):
        assert expected in text


def test_semdogfood_report_preserves_command_level_verification_and_runtime_paths():
    text = _normalized(EVIDENCE)

    for expected in (
        "uv run pytest tests/test_dispatcher.py -q --no-cov -k \"phase_plan or garecut or SEMWALKGAP or markdown or lexical\"",
        "env OPENAI_API_KEY=dummy-local-key uv run pytest tests/test_git_index_manager.py tests/test_repository_commands.py -q --no-cov -k \"phase_plan or garecut or SEMWALKGAP or lexical or interrupted or boundary\"",
        "uv run pytest tests/docs/test_semdogfood_evidence_contract.py -q --no-cov",
        "timeout 120s env OPENAI_API_KEY=dummy-local-key uv run mcp-index repository sync --force-full",
        "env OPENAI_API_KEY=dummy-local-key uv run mcp-index repository status",
        "sed -n '1,240p' .mcp-index/force_full_exit_trace.json",
        "force_full_exit_trace.json",
        "sqlite3 .mcp-index/current.db 'select count(*) from files; select count(*) from code_chunks; select count(*) from chunk_summaries; select count(*) from semantic_points;'",
        "mcp_server/dispatcher/dispatcher_enhanced.py",
        "mcp_server/cli/repository_commands.py",
        ".devcontainer/devcontainer.json",
        "tests/test_deployment_runbook_shape.py",
        "tests/test_reindex_resume.py",
        "scripts/run_test_batch.py",
        "scripts/validate_mcp_comprehensive.py",
        "scripts/migrate_large_index_to_multi_repo.py",
        "scripts/check_index_languages.py",
        "tests/root_tests/test_voyage_api.py",
        "tests/root_tests/run_reranking_tests.py",
        "scripts/quick_mcp_vs_native_validation.py",
        "tests/test_artifact_publish_race.py",
        "analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "analysis_archive/semantic_vs_sql_comparison_1750926162.json",
        "tests/docs/test_mre2e_evidence_contract.py",
        "tests/docs/test_gagov_governance_contract.py",
        ".claude/commands/execute-lane.md",
        ".claude/commands/plan-phase.md",
        "plans/phase-plan-v7-SEMPREFLIGHT.md",
        "plans/phase-plan-v7-SEMDOCGOV.md",
        "plans/phase-plan-v5-garecut.md",
        "plans/phase-plan-v7-SEMWALKGAP.md",
        "plans/phase-plan-v7-SEMSYNCFIX.md",
        "plans/phase-plan-v7-SEMVISUALREPORT.md",
        "Last sync error:",
        "disk I/O error",
        "Trace status: `interrupted`",
        "Trace stage: `lexical_walking`",
        "Trace stage family: `lexical`",
        "Trace blocker source: `lexical_mutation`",
        "semantic_source: \"semantic\"",
        "semantic_collection_name: \"code_index__oss_high__v1\"",
        "local multi-repo dogfooding",
        "Lexical boundary: using exact bounded Python indexing for mcp_server/visualization/quick_charts.py",
        "Lexical boundary: using exact bounded Python indexing for tests/docs/test_mre2e_evidence_contract.py -> tests/docs/test_gagov_governance_contract.py",
        "Lexical boundary: using exact bounded Markdown indexing for .claude/commands/execute-lane.md -> .claude/commands/plan-phase.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/validation/ga-closeout-decision.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/validation/mre2e-evidence.md",
        "Lexical boundary: using exact bounded Markdown indexing for docs/benchmarks/mcp_vs_native_benchmark_fullrepo_fireworks_qwen_voyage_local_iter5_rerun.md -> docs/benchmarks/production_benchmark.md",
        "Lexical boundary: using exact bounded Python indexing for scripts/migrate_large_index_to_multi_repo.py -> scripts/check_index_languages.py",
        "Lexical boundary: using exact bounded JSON indexing for analysis_archive/semantic_vs_sql_comparison_1750926162.json after analysis_archive/scripts_archive/scripts_test_files/verify_mcp_fix.py",
        "fixture repositories under test_workspace/ are ignored during lexical walking",
        "SEMPHASEPLANS acceptance is satisfied for its named blocker",
        "SEMCROSSPLANS acceptance is satisfied for its named blocker",
        "repository status` still advertises only the earlier bounded lexical surfaces",
        "Phase plan: `plans/phase-plan-v7-SEMCROSSPLANS.md`",
        "Prior phase plan: `plans/phase-plan-v7-SEMPHASEPLANS.md`",
    ):
        assert expected in text
